@startuml location(sprint 1)
left to right direction
actor "admin" as ad
rectangle location {
  usecase "add LOAN" as UC1
  usecase "show LOAN list" as UC2
  usecase "update LOAN info" as UC3
}
ad -- UC1
ad -- UC2
ad -- UC3
@enduml